language: c
addons:
  apt:
    update: true
    packages:
      - libncurses-dev
      - libreadline-dev
      - build-essential
      - libpq-dev
before_script:
  - ./configure
script: 
  - make
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
env:
  global:
  - CODECOV_TOKEN=f5247bfc-2837-40e7-b4f8-285ad10c7dfc
